version: "3.9"

services:
  db:
    container_name: pg_db
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "49154:5432"
      
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: studyemoji@mail.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
    - "5051:80"
    